from . import real_estate
from . import type_demand
from . import estate_direction
from . import secondary_form
from . import estate_way
from . import estate_stair
from . import type_estate
from . import estate_style
from . import group_style
from . import estate_structure
from . import role_estate
from . import role_detail
from . import res_partner
from . import group_direction
from . import real_estate_search
from . import demand_estate_search
from . import res_config_settings
from . import real_estate_search_expired
from . import search_demand_estate_customer
from . import offering_estate
from . import call_sale_estate
from . import offering_history
from . import search_demand_estate_customer
from . import real_estate_prices_config
from . import real_estate_advertising_template
from . import real_estate_favorite
from . import import_image_log
from . import estate_category
